# Copyright (c) 2025-2026 G & R Associates LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Phase 10.J.post-8.5.5: three NEW productive redup paradigm
cells per the reviewer's productivity-not-attestation principle.

Fifth sub-PR in the post-8.5.N series. Three productive
reduplication patterns added as paradigm cells (rather than
direct-lex entries) per the reviewer 2026-05-30 ruling:

> "balu-baluktot is a synchronically productive reduplicative
> derivative, not a lexicalized simplex form. ... Treat balu-
> baluktot as a derived form generated by a productive
> reduplicative process. Do not treat it as an unanalyzable
> lexicalized stem unless you find evidence of semantic
> idiosyncrasy or historical fossilization."

The same principle applies to `nakababata` (productive `naka-CV-X`
comparative family) and `tulung-tulong` (productive collaborative-
manner redup family).

## Three new paradigm cells

### (a) `naka_cv_compar` — NOUN/ADJ → comparative ADJ

Productive family: `nakababata` "younger" (from `bata`),
`nakatatanda` "older" (from `tanda`), `nakabubuti` "better"
(from `buti`), `nakapapagod` "tiring" (from `pagod`),
`nakahihigit` "surpasses" (from `higit`).

Operation chain: `cv_redup` → `prefix("ka")` → `prefix("na")`.
Produces `na` + `ka` + `<cv-redup-stem>` = `nakababata` from
`bata`.

Per-root opt-in via `affix_class: [naka_cv_compar]`. Currently
`bata` opts in (PAMILYA/sent-14 attestation).

### (b) `adj_cv2_redup` — ADJ first-2-syllable redup (intensive)

Productive family per the reviewer (2026-05-30 informant):
`balubaluktot` "very crooked" (from `baluktot`),
`sari-sarili` "various selves" (from `sarili`),
`halo-halo` "mixed mixture" (from `halo` — though halo is shorter),
`iba-iba` "various" (from `iba`).

NEW operation: `cv2_redup` — prepends the first 2 syllables
(`first_cvcv`) of the ROOT before the ROOT. Distinct from
`cv_redup` (single CV) and `redup_root` (full root).

`first_cvcv` walks the ROOT to find the first 2 vowels and
returns the slice up to (and including) the second vowel.
`baluktot` → `balu`; `mahaba` → `maha`; `matalino` → `mata`.

Per-root opt-in via `affix_class: [adj_cv2_redup]`. Currently
`baluktot` opts in. The class is in `_ADDITIVE_ADJ_AFFIX_CLASSES`
so the bare root stays indexed alongside the cv2 derivation.

REDUP=FULL + REDUP_SEM=INTENS feats (10.B convention).

### (c) `v_collab_redup` — VERB → collaborative-manner ADV

Productive family: `tulung-tulong` "collaboratively, in mutual
help" (from `tulong`), parallel to `sama-sama` "together"
(samasama covered by post-8.5.4 VERB lex), `kani-kanya` "each
one's", etc. Same morphological pattern as Phase 10.A
`time_redup_freq` (`araw-araw`) and Phase 10.B
`place_redup_distr` (`bahay-bahay`) but with VERB→ADV POS-flip
+ COLLABORATIVE=true semantics.

Operations: `[redup_root]` — single op, full-root redup with
`lemma_redup_hyphen: true` for canonical `tulung-tulong`
LEMMA. Per-root `redup_o_raise` sandhi raises the first-copy
stem-final /o/ to /u/.

Per-root opt-in via `affix_class: [v_collab_redup]`. Currently
`tulong` opts in.

New `COLLABORATIVE` feat in BINARY_FEATS (66 → 67).

## Audit signal (post-8.5.4 → post-8.5.5)

0 audit closures (foundational paradigm work — like post-8.5.1
the lex completions). The wave-1 sentences with these forms
(`nakababata` in PAMILYA/sent-14; `balubaluktot` in PAG-AARAL/
sent-8) ZPF for unrelated structural issues
(3-way `ang`-NP coord, `Pinipilit nilang magsalita` control
gap, etc.). 6 unattributed exemplars demonstrate parse-readiness.
"""

from tgllfg.core.pipeline import parse_text
from tgllfg.morph.analyzer import _get_default
from tgllfg.morph.sandhi import first_cvcv, cv2_reduplicate


class TestCv2Reduplicate:
    """post-8.5.5 (b): the new ``cv2_redup`` op + ``first_cvcv``
    helper."""

    def test_first_cvcv_cvcv(self) -> None:
        """``baluktot`` (b-a-l-u-k-t-o-t): first 2 syllables = ba-lu."""
        assert first_cvcv("baluktot") == "balu"

    def test_first_cvcv_cvcv2(self) -> None:
        """``matalino`` (m-a-t-a-l-i-n-o): first 2 syllables = ma-ta."""
        assert first_cvcv("matalino") == "mata"

    def test_first_cvcv_short(self) -> None:
        """Single-syllable base returns full base."""
        assert first_cvcv("ka") == "ka"

    def test_first_cvcv_vowel_initial(self) -> None:
        """V-initial: ``alis`` (a-l-i-s) → first 2 vowels = a-i = ``ali``."""
        assert first_cvcv("alis") == "ali"

    def test_cv2_reduplicate(self) -> None:
        assert cv2_reduplicate("baluktot") == "balubaluktot"


class TestNakaCvComparCell:
    """post-8.5.5 (a): ``naka_cv_compar`` cell — NOUN→ADJ
    comparative."""

    def test_nakababata_known(self) -> None:
        analyzer = _get_default()
        assert analyzer.is_known_surface("nakababata")

    def test_nakababata_predicative(self) -> None:
        parses = parse_text("Sila ay nakababata.", n_best=1)
        assert len(parses) >= 1

    def test_ang_mga_nakababata(self) -> None:
        parses = parse_text("Ang mga bata ay nakababata.", n_best=1)
        assert len(parses) >= 1


class TestAdjCv2RedupCell:
    """post-8.5.5 (b): ``adj_cv2_redup`` cell — first-2-syllable
    redup intensive."""

    def test_balubaluktot_known(self) -> None:
        analyzer = _get_default()
        assert analyzer.is_known_surface("balubaluktot")

    def test_baluktot_bare_preserved(self) -> None:
        """``adj_cv2_redup`` is in ``_ADDITIVE_ADJ_AFFIX_CLASSES``
        so the bare root stays indexed alongside the cv2 form."""
        analyzer = _get_default()
        assert analyzer.is_known_surface("baluktot")

    def test_balubaluktot_predicative(self) -> None:
        parses = parse_text("Ang aklat ay balubaluktot.", n_best=1)
        assert len(parses) >= 1

    def test_balubaluktot_bare(self) -> None:
        parses = parse_text("Balubaluktot ang kahoy.", n_best=1)
        assert len(parses) >= 1


class TestVCollabRedupCell:
    """post-8.5.5 (c): ``v_collab_redup`` cell — VERB→ADV
    collaborative-manner redup."""

    def test_tulungtulong_known(self) -> None:
        """The cell produces the joined form ``tulungtulong``
        (hyphen-merge tokenizer pre-pass collapses ``tulung-
        tulong`` to this surface)."""
        analyzer = _get_default()
        assert analyzer.is_known_surface("tulungtulong")

    def test_tulung_tulong_parses(self) -> None:
        parses = parse_text("Tulung-tulong sila.", n_best=1)
        assert len(parses) >= 1

    def test_collaborative_feat_in_binary_registry(self) -> None:
        from tgllfg.core.feats import BINARY_FEATS
        assert "COLLABORATIVE" in BINARY_FEATS


class TestKahitAdjConcessive:
    """post-8.5.5 anti-deferral: `Kahit ADJ, S` PRO-pivot
    concessive — closes PAG-AARAL/sent-8."""

    def test_kahit_balubaluktot_pinipilit(self) -> None:
        """The full PAG-AARAL/sent-8."""
        parses = parse_text(
            "Kahi't balubaluktot, pinipilit nilang magsalita.",
            n_best=1,
        )
        assert len(parses) >= 1

    def test_kahit_malaki_kumain(self) -> None:
        """``Kahit malaki, kumain siya.`` — bare ADJ concessive."""
        parses = parse_text("Kahit malaki, kumain siya.", n_best=1)
        assert len(parses) >= 1

    def test_kahit_overt_subj_preserved(self) -> None:
        """``Kahit malaki ka, kumain ka.`` — overt-SUBJ concessive
        (via existing SubordClause → PART[CONC] S rule) preserved."""
        parses = parse_text("Kahit malaki ka, kumain ka.", n_best=1)
        assert len(parses) >= 1


class TestPilitProControl:
    """post-8.5.5 anti-deferral: PRO-NOM-pivot TRANS-control —
    `V[CTRL_CLASS=TRANS] NP[GEN] PART[LK] S_XCOMP`."""

    def test_pinipilit_nilang_magsalita(self) -> None:
        """The PAG-AARAL/sent-8 second clause in isolation."""
        parses = parse_text("Pinipilit nilang magsalita.", n_best=1)
        assert len(parses) >= 1

    def test_pinipilit_kong_kumain(self) -> None:
        parses = parse_text("Pinipilit kong kumain.", n_best=1)
        assert len(parses) >= 1

    def test_pinilit_nilang_magsalita(self) -> None:
        """PFV variant of the bare-PRO TRANS-control."""
        parses = parse_text("Pinilit nilang magsalita.", n_best=1)
        assert len(parses) >= 1

    def test_overt_pivot_trans_preserved(self) -> None:
        """``Pinipilit nila siyang magsalita.`` — the existing
        TRANS rule with overt NOM-pivot continues to parse."""
        parses = parse_text(
            "Pinipilit nila siyang magsalita.", n_best=1,
        )
        assert len(parses) >= 1


class TestAntiRegression:
    """post-8.5.5 anti-regression: existing redup cells unchanged."""

    def test_cv_redup_unchanged(self) -> None:
        """``cv_redup`` (single CV) still produces ``kakain`` from
        ``kain``. Adding the new ``cv2_redup`` op is additive."""
        from tgllfg.morph.sandhi import cv_reduplicate
        assert cv_reduplicate("kain") == "kakain"
        assert cv_reduplicate("baluktot") == "babaluktot"

    def test_existing_tulong_paradigm_preserved(self) -> None:
        """``tumulong`` (AV PFV), ``tumutulong`` (AV IPFV),
        ``pagtulong`` (gerund) all continue to derive — the new
        ``v_collab_redup`` opt-in is additive."""
        analyzer = _get_default()
        assert analyzer.is_known_surface("tumulong")
        assert analyzer.is_known_surface("tumutulong")
        assert analyzer.is_known_surface("pagtulong")

    def test_existing_bata_preserved(self) -> None:
        """``bata`` NOUN still analyzes as such — opting into
        ``naka_cv_compar`` is additive."""
        analyzer = _get_default()
        assert analyzer.is_known_surface("bata")

    def test_existing_adj_redup_unaffected(self) -> None:
        """Roots opting into ``adj_redup`` (full X-X redup like
        ``gandaganda``) still work — the new ``adj_cv2_redup`` is
        a separate affix_class."""
        analyzer = _get_default()
        # ganda has adj_redup → gandaganda
        assert analyzer.is_known_surface("gandaganda")
