# Copyright (c) 2025-2026 G & R Associates LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Phase 12.final: ``docs/grammar.md`` stays in sync with the cfg/ rules.

The grammar reference is regenerated by ``tgllfg docs grammar`` (the
shared :mod:`tgllfg.docs.grammar`); this gate asserts the committed file
matches a fresh render, so a grammar change that isn't re-rendered fails
CI (the "generate + check-in-sync" pattern, as for the audit baseline).
"""

from tgllfg.docs import GRAMMAR_DOC_PATH, render_grammar_doc


def test_grammar_doc_in_sync() -> None:
    expected = render_grammar_doc()
    actual = GRAMMAR_DOC_PATH.read_text(encoding="utf-8")
    assert actual == expected, (
        "docs/grammar.md is stale — regenerate with `tgllfg docs grammar`"
    )
