# Copyright (c) 2025-2026 G & R Associates LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Phase 13.D: the committed openapi.json stays in sync with the app.

``openapi.json`` is regenerated by ``tgllfg openapi`` (the shared
:mod:`tgllfg.api.openapi`); this gate asserts the committed file matches
a fresh render, so a route / DTO change that isn't re-rendered fails CI
(the "generate + check-in-sync" pattern, as for the audit baseline and
docs/grammar.md). The complementary CI step ``tgllfg openapi --check``
runs on every push.
"""

import json

from tgllfg.api import OPENAPI_PATH, render_openapi


def test_openapi_in_sync() -> None:
    expected = render_openapi()
    actual = OPENAPI_PATH.read_text(encoding="utf-8")
    assert actual == expected, "openapi.json is stale — run `tgllfg openapi`"


def test_openapi_lists_the_routes() -> None:
    paths = json.loads(render_openapi())["paths"]
    for route in (
        "/api/v1/parse",
        "/api/v1/lex/search",
        "/api/v1/audit/run",
        "/api/v1/audit/runs/{run_id}",
        "/api/v1/audit/diff",
        "/health",
        "/ready",
    ):
        assert route in paths, f"missing route in openapi: {route}"
