// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuditDiffApiV1AuditDiffPostData, AuditDiffApiV1AuditDiffPostErrors, AuditDiffApiV1AuditDiffPostResponses, AuditRunApiV1AuditRunPostData, AuditRunApiV1AuditRunPostErrors, AuditRunApiV1AuditRunPostResponses, AuditRunStatusApiV1AuditRunsRunIdGetData, AuditRunStatusApiV1AuditRunsRunIdGetErrors, AuditRunStatusApiV1AuditRunsRunIdGetResponses, HealthHealthGetData, HealthHealthGetResponses, LexSearchApiV1LexSearchGetData, LexSearchApiV1LexSearchGetErrors, LexSearchApiV1LexSearchGetResponses, ParseEndpointApiV1ParsePostData, ParseEndpointApiV1ParsePostErrors, ParseEndpointApiV1ParsePostResponses, ReadyReadyGetData, ReadyReadyGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Liveness: the process is up and serving. No external deps.
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

/**
 * Ready
 *
 * Readiness: DB reachable **and** the compiled grammar warmed.
 * Returns ``503`` with a per-check breakdown until both hold.
 */
export const readyReadyGet = <ThrowOnError extends boolean = false>(options?: Options<ReadyReadyGetData, ThrowOnError>): RequestResult<ReadyReadyGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadyReadyGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ready',
    ...options
});

/**
 * Parse a Tagalog sentence
 */
export const parseEndpointApiV1ParsePost = <ThrowOnError extends boolean = false>(options: Options<ParseEndpointApiV1ParsePostData, ThrowOnError>): RequestResult<ParseEndpointApiV1ParsePostResponses, ParseEndpointApiV1ParsePostErrors, ThrowOnError> => (options.client ?? client).post<ParseEndpointApiV1ParsePostResponses, ParseEndpointApiV1ParsePostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/parse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fuzzy lemma search
 */
export const lexSearchApiV1LexSearchGet = <ThrowOnError extends boolean = false>(options: Options<LexSearchApiV1LexSearchGetData, ThrowOnError>): RequestResult<LexSearchApiV1LexSearchGetResponses, LexSearchApiV1LexSearchGetErrors, ThrowOnError> => (options.client ?? client).get<LexSearchApiV1LexSearchGetResponses, LexSearchApiV1LexSearchGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/lex/search',
    ...options
});

/**
 * Start a corpus audit (background job)
 */
export const auditRunApiV1AuditRunPost = <ThrowOnError extends boolean = false>(options: Options<AuditRunApiV1AuditRunPostData, ThrowOnError>): RequestResult<AuditRunApiV1AuditRunPostResponses, AuditRunApiV1AuditRunPostErrors, ThrowOnError> => (options.client ?? client).post<AuditRunApiV1AuditRunPostResponses, AuditRunApiV1AuditRunPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audit/run',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Poll an audit run's status
 */
export const auditRunStatusApiV1AuditRunsRunIdGet = <ThrowOnError extends boolean = false>(options: Options<AuditRunStatusApiV1AuditRunsRunIdGetData, ThrowOnError>): RequestResult<AuditRunStatusApiV1AuditRunsRunIdGetResponses, AuditRunStatusApiV1AuditRunsRunIdGetErrors, ThrowOnError> => (options.client ?? client).get<AuditRunStatusApiV1AuditRunsRunIdGetResponses, AuditRunStatusApiV1AuditRunsRunIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audit/runs/{run_id}',
    ...options
});

/**
 * Diff the latest results against the baseline
 */
export const auditDiffApiV1AuditDiffPost = <ThrowOnError extends boolean = false>(options: Options<AuditDiffApiV1AuditDiffPostData, ThrowOnError>): RequestResult<AuditDiffApiV1AuditDiffPostResponses, AuditDiffApiV1AuditDiffPostErrors, ThrowOnError> => (options.client ?? client).post<AuditDiffApiV1AuditDiffPostResponses, AuditDiffApiV1AuditDiffPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audit/diff',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
