// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuditDiffData, AuditDiffErrors, AuditDiffResponses, AuditRunData, AuditRunErrors, AuditRunResponses, AuditRunStatusData, AuditRunStatusErrors, AuditRunStatusResponses, HealthData, HealthResponses, LexSearchData, LexSearchErrors, LexSearchResponses, ParseData, ParseErrors, ParseResponses, ReadyData, ReadyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Liveness: the process is up and serving. No external deps.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

/**
 * Ready
 *
 * Readiness: DB reachable **and** the compiled grammar warmed.
 * Returns ``503`` with a per-check breakdown until both hold.
 */
export const ready = <ThrowOnError extends boolean = false>(options?: Options<ReadyData, ThrowOnError>): RequestResult<ReadyResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ready',
    ...options
});

/**
 * Parse a Tagalog sentence
 */
export const parse = <ThrowOnError extends boolean = false>(options: Options<ParseData, ThrowOnError>): RequestResult<ParseResponses, ParseErrors, ThrowOnError> => (options.client ?? client).post<ParseResponses, ParseErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/parse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fuzzy lemma search
 */
export const lexSearch = <ThrowOnError extends boolean = false>(options: Options<LexSearchData, ThrowOnError>): RequestResult<LexSearchResponses, LexSearchErrors, ThrowOnError> => (options.client ?? client).get<LexSearchResponses, LexSearchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/lex/search',
    ...options
});

/**
 * Start a corpus audit (background job)
 */
export const auditRun = <ThrowOnError extends boolean = false>(options: Options<AuditRunData, ThrowOnError>): RequestResult<AuditRunResponses, AuditRunErrors, ThrowOnError> => (options.client ?? client).post<AuditRunResponses, AuditRunErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audit/run',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Poll an audit run's status
 */
export const auditRunStatus = <ThrowOnError extends boolean = false>(options: Options<AuditRunStatusData, ThrowOnError>): RequestResult<AuditRunStatusResponses, AuditRunStatusErrors, ThrowOnError> => (options.client ?? client).get<AuditRunStatusResponses, AuditRunStatusErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audit/runs/{run_id}',
    ...options
});

/**
 * Diff the latest results against the baseline
 */
export const auditDiff = <ThrowOnError extends boolean = false>(options: Options<AuditDiffData, ThrowOnError>): RequestResult<AuditDiffResponses, AuditDiffErrors, ThrowOnError> => (options.client ?? client).post<AuditDiffResponses, AuditDiffErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audit/diff',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
