// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AStructureModel
 */
export type AStructureModel = {
    /**
     * Pred
     */
    pred: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Mapping
     */
    mapping: {
        [key: string]: string;
    };
};

/**
 * AuditDiffModel
 */
export type AuditDiffModel = {
    /**
     * Has Regressions
     */
    has_regressions: boolean;
    /**
     * Counts
     */
    counts: {
        [key: string]: number;
    };
    /**
     * Regressions
     */
    regressions: Array<DiffEntryModel>;
    /**
     * Improvements
     */
    improvements: Array<DiffEntryModel>;
};

/**
 * AuditDiffRequest
 */
export type AuditDiffRequest = {
    /**
     * Waves
     *
     * Wave ids to diff (default: all waves with results).
     */
    waves?: Array<string> | null;
};

/**
 * AuditRunRequest
 */
export type AuditRunRequest = {
    /**
     * Waves
     *
     * Wave ids to audit (default: all waves).
     */
    waves?: Array<string> | null;
};

/**
 * AuditRunStatus
 */
export type AuditRunStatus = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: 'running' | 'completed' | 'failed' | 'cancelled';
    summary?: RunSummaryModel | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * CNodeModel
 */
export type CNodeModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Children
     */
    children?: Array<string>;
    /**
     * Equations
     */
    equations?: Array<string>;
};

/**
 * CStructure
 */
export type CStructure = {
    /**
     * Root
     */
    root: string;
    /**
     * Nodes
     */
    nodes: {
        [key: string]: CNodeModel;
    };
};

/**
 * DiagnosticModel
 */
export type DiagnosticModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Message
     */
    message: string;
    /**
     * Path
     */
    path?: Array<string>;
    /**
     * Equation
     */
    equation?: string | null;
    /**
     * Cnode Label
     */
    cnode_label?: string | null;
    /**
     * Blocking
     */
    blocking?: boolean;
    /**
     * Detail
     */
    detail?: {
        [key: string]: unknown;
    };
};

/**
 * DiffEntryModel
 */
export type DiffEntryModel = {
    /**
     * Source
     */
    source: string;
    /**
     * Locator
     */
    locator: string;
    /**
     * Before
     */
    before: string;
    /**
     * After
     */
    after: string;
    /**
     * Text
     */
    text: string;
};

/**
 * FNodeModel
 */
export type FNodeModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Feats
     */
    feats?: {
        [key: string]: unknown;
    };
};

/**
 * FStructureModel
 */
export type FStructureModel = {
    /**
     * Root
     */
    root: string;
    /**
     * Nodes
     */
    nodes: {
        [key: string]: FNodeModel;
    };
};

/**
 * FragmentModel
 */
export type FragmentModel = {
    /**
     * Span
     */
    span: [
        number,
        number
    ];
    c_structure: CStructure;
    f_structure: FStructureModel;
    a_structure: AStructureModel;
    /**
     * Diagnostics
     */
    diagnostics?: Array<DiagnosticModel>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LemmaMatchModel
 */
export type LemmaMatchModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Language Id
     */
    language_id: string;
    /**
     * Citation Form
     */
    citation_form: string;
    /**
     * Pos
     */
    pos: string;
    /**
     * Gloss
     */
    gloss?: string | null;
    /**
     * Score
     */
    score: number;
};

/**
 * LexSearchResponse
 */
export type LexSearchResponse = {
    /**
     * Query
     */
    query: string;
    /**
     * Matches
     */
    matches: Array<LemmaMatchModel>;
};

/**
 * ParseMeta
 */
export type ParseMeta = {
    /**
     * N Best
     */
    n_best: number;
    /**
     * Parse Count
     */
    parse_count: number;
    /**
     * Fragment Count
     */
    fragment_count: number;
};

/**
 * ParseModel
 */
export type ParseModel = {
    /**
     * Id
     */
    id: string;
    c_structure: CStructure;
    f_structure: FStructureModel;
    a_structure: AStructureModel;
    /**
     * Diagnostics
     */
    diagnostics?: Array<DiagnosticModel>;
};

/**
 * ParseRequest
 */
export type ParseRequest = {
    /**
     * Text
     *
     * The Tagalog sentence to parse.
     */
    text: string;
    /**
     * N Best
     *
     * Cap on the number of complete parses returned.
     */
    n_best?: number;
    /**
     * Strict
     *
     * Suppress fragment output when no complete parse is found (mirrors `tgllfg parse --strict`).
     */
    strict?: boolean;
};

/**
 * ParseResponse
 */
export type ParseResponse = {
    /**
     * Text
     */
    text: string;
    /**
     * Parses
     */
    parses?: Array<ParseModel>;
    /**
     * Fragments
     */
    fragments?: Array<FragmentModel>;
    meta: ParseMeta;
};

/**
 * RunSummaryModel
 */
export type RunSummaryModel = {
    /**
     * Elapsed S
     */
    elapsed_s: number;
    /**
     * N Workers
     */
    n_workers: number;
    /**
     * N Tasks
     */
    n_tasks: number;
    /**
     * Waves
     */
    waves: Array<WaveSummaryModel>;
    /**
     * Total Ok
     */
    total_ok: number;
    /**
     * Total
     */
    total: number;
    /**
     * Total Pct
     */
    total_pct: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WaveSummaryModel
 */
export type WaveSummaryModel = {
    /**
     * Wave Id
     */
    wave_id: string;
    /**
     * Ok
     */
    ok: number;
    /**
     * Total
     */
    total: number;
    /**
     * Pct
     */
    pct: number;
    /**
     * Timeouts
     */
    timeouts: number;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ReadyReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ParseEndpointApiV1ParsePostData = {
    body: ParseRequest;
    path?: never;
    query?: never;
    url: '/api/v1/parse';
};

export type ParseEndpointApiV1ParsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseEndpointApiV1ParsePostError = ParseEndpointApiV1ParsePostErrors[keyof ParseEndpointApiV1ParsePostErrors];

export type ParseEndpointApiV1ParsePostResponses = {
    /**
     * Successful Response
     */
    200: ParseResponse;
};

export type ParseEndpointApiV1ParsePostResponse = ParseEndpointApiV1ParsePostResponses[keyof ParseEndpointApiV1ParsePostResponses];

export type LexSearchApiV1LexSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Fuzzy query against lemma citation forms.
         */
        q: string;
        /**
         * Limit
         *
         * Max matches to return.
         */
        limit?: number;
    };
    url: '/api/v1/lex/search';
};

export type LexSearchApiV1LexSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LexSearchApiV1LexSearchGetError = LexSearchApiV1LexSearchGetErrors[keyof LexSearchApiV1LexSearchGetErrors];

export type LexSearchApiV1LexSearchGetResponses = {
    /**
     * Successful Response
     */
    200: LexSearchResponse;
};

export type LexSearchApiV1LexSearchGetResponse = LexSearchApiV1LexSearchGetResponses[keyof LexSearchApiV1LexSearchGetResponses];

export type AuditRunApiV1AuditRunPostData = {
    body: AuditRunRequest;
    path?: never;
    query?: never;
    url: '/api/v1/audit/run';
};

export type AuditRunApiV1AuditRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditRunApiV1AuditRunPostError = AuditRunApiV1AuditRunPostErrors[keyof AuditRunApiV1AuditRunPostErrors];

export type AuditRunApiV1AuditRunPostResponses = {
    /**
     * Successful Response
     */
    202: AuditRunStatus;
};

export type AuditRunApiV1AuditRunPostResponse = AuditRunApiV1AuditRunPostResponses[keyof AuditRunApiV1AuditRunPostResponses];

export type AuditRunStatusApiV1AuditRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/audit/runs/{run_id}';
};

export type AuditRunStatusApiV1AuditRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditRunStatusApiV1AuditRunsRunIdGetError = AuditRunStatusApiV1AuditRunsRunIdGetErrors[keyof AuditRunStatusApiV1AuditRunsRunIdGetErrors];

export type AuditRunStatusApiV1AuditRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: AuditRunStatus;
};

export type AuditRunStatusApiV1AuditRunsRunIdGetResponse = AuditRunStatusApiV1AuditRunsRunIdGetResponses[keyof AuditRunStatusApiV1AuditRunsRunIdGetResponses];

export type AuditDiffApiV1AuditDiffPostData = {
    body: AuditDiffRequest;
    path?: never;
    query?: never;
    url: '/api/v1/audit/diff';
};

export type AuditDiffApiV1AuditDiffPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuditDiffApiV1AuditDiffPostError = AuditDiffApiV1AuditDiffPostErrors[keyof AuditDiffApiV1AuditDiffPostErrors];

export type AuditDiffApiV1AuditDiffPostResponses = {
    /**
     * Successful Response
     */
    200: AuditDiffModel;
};

export type AuditDiffApiV1AuditDiffPostResponse = AuditDiffApiV1AuditDiffPostResponses[keyof AuditDiffApiV1AuditDiffPostResponses];
