"""Baseline schema for the tgllfg lexicon (plan §6.2).

Revision ID: 0001
Revises:
Create Date: 2026-04-29

Creates every table the parser will eventually read from, plus the two
PostgreSQL extensions the schema depends on (``pgcrypto`` for
``gen_random_uuid()`` UUID defaults, ``pg_trgm`` for fuzzy lemma
lookup) and the indexes specified in §6.2.

The migration is intentionally hand-written rather than autogenerated
from ORM models — Phase 3 Commit 3 introduces the SQLAlchemy models,
which will be authored *to match* this schema rather than the other
way around.

Naming deviation from the plan: the plan's ``metadata`` table is named
``lex_metadata`` here to avoid collision with SQLAlchemy's
``Base.metadata`` attribute when the ORM models land. The plan's
``data_version`` field lives in ``lex_metadata.value`` keyed by
``data_version``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    uuid_pk = sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )

    op.create_table(
        "language",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("iso_code", sa.Text, nullable=False, unique=True),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "source",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("short_name", sa.Text, nullable=False, unique=True),
        sa.Column("full_citation", sa.Text, nullable=False),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "lemma",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("citation_form", sa.Text, nullable=False),
        sa.Column("pos", sa.Text, nullable=False),
        sa.Column("gloss", sa.Text),
        sa.Column("notes", sa.Text),
        sa.Column("source_ref", sa.Text),
        sa.UniqueConstraint("language_id", "citation_form", "pos", name="uq_lemma_lang_form_pos"),
    )
    op.create_index("ix_lemma_lang_form", "lemma", ["language_id", "citation_form"])
    op.execute(
        "CREATE INDEX ix_lemma_citation_form_trgm "
        "ON lemma USING gin (citation_form gin_trgm_ops)"
    )

    op.create_table(
        "lex_entry",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "lemma_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("lemma.id"),
            nullable=False,
        ),
        sa.Column("pred_template", sa.Text, nullable=False),
        sa.Column("a_structure", postgresql.JSONB, nullable=False),
        sa.Column("morph_constraints", postgresql.JSONB, nullable=False),
        sa.Column("intrinsic_classification", postgresql.JSONB, nullable=False),
        sa.Column("default_mapping", postgresql.JSONB, nullable=True),
        sa.Column("notes", sa.Text),
    )
    op.create_index("ix_lex_entry_lemma", "lex_entry", ["lemma_id"])

    op.create_table(
        "affix",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("shape", sa.Text, nullable=False),
        sa.Column("type", sa.Text, nullable=False),
        sa.Column("features", postgresql.JSONB, nullable=False),
        sa.Column("position", sa.Integer),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "paradigm",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("name", sa.Text, nullable=False),
    )

    op.create_table(
        "paradigm_slot",
        sa.Column(
            "paradigm_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("paradigm.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer, nullable=False),
        sa.Column(
            "affix_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("affix.id"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("paradigm_id", "position"),
    )

    op.create_table(
        "sandhi_rule",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("pattern", sa.Text, nullable=False),
        sa.Column("replacement", sa.Text, nullable=False),
        sa.Column("conditions", postgresql.JSONB, nullable=False),
        sa.Column("ordering", sa.Integer, nullable=False),
    )

    op.create_table(
        "particle",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("surface", sa.Text, nullable=False),
        sa.Column("pos", sa.Text, nullable=False),
        sa.Column("features", postgresql.JSONB, nullable=False),
        sa.Column(
            "is_clitic",
            sa.Boolean,
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
        sa.Column("clitic_class", sa.Text),
        sa.Column("notes", sa.Text),
    )
    op.create_index("ix_particle_lang_surface", "particle", ["language_id", "surface"])

    op.create_table(
        "pronoun",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("surface", sa.Text, nullable=False),
        sa.Column("features", postgresql.JSONB, nullable=False),
        sa.Column(
            "is_clitic",
            sa.Boolean,
            nullable=False,
            server_default=sa.text("FALSE"),
        ),
    )

    op.create_table(
        "example",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("source_ref", sa.Text),
        sa.Column("expected_c", postgresql.JSONB),
        sa.Column("expected_f", postgresql.JSONB),
        sa.Column("expected_a", postgresql.JSONB),
        sa.Column("notes", sa.Text),
    )
    op.execute(
        "CREATE INDEX ix_example_text_fts "
        "ON example USING gin (to_tsvector('simple', text))"
    )

    op.create_table(
        "voice_alias",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "language_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("language.id"),
            nullable=False,
        ),
        sa.Column("label", sa.Text, nullable=False),
        sa.Column("voice", sa.Text, nullable=False),
        sa.Column("appl", sa.Text),
        sa.Column("caus", sa.Text),
        sa.Column("notes", sa.Text),
        sa.UniqueConstraint("language_id", "label", name="uq_voice_alias_lang_label"),
    )

    op.create_table(
        "lex_metadata",
        sa.Column("key", sa.Text, primary_key=True),
        sa.Column("value", sa.Text, nullable=False),
    )

    _ = uuid_pk  # silence unused; kept for parity-of-definition above


def downgrade() -> None:
    op.drop_table("lex_metadata")
    op.drop_table("voice_alias")
    op.execute("DROP INDEX IF EXISTS ix_example_text_fts")
    op.drop_table("example")
    op.drop_table("pronoun")
    op.drop_index("ix_particle_lang_surface", table_name="particle")
    op.drop_table("particle")
    op.drop_table("sandhi_rule")
    op.drop_table("paradigm_slot")
    op.drop_table("paradigm")
    op.drop_table("affix")
    op.drop_index("ix_lex_entry_lemma", table_name="lex_entry")
    op.drop_table("lex_entry")
    op.execute("DROP INDEX IF EXISTS ix_lemma_citation_form_trgm")
    op.drop_index("ix_lemma_lang_form", table_name="lemma")
    op.drop_table("lemma")
    op.drop_table("source")
    op.drop_table("language")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
