# Copyright (c) 2025-2026 G & R Associates LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Phase 12.final: the c-structure grammar reference generator.

:func:`render_grammar_doc` builds the markdown for ``docs/grammar.md`` —
every ``Rule`` composed by :meth:`tgllfg.cfg.grammar.Grammar.load_default`,
grouped by base non-terminal (the category before any ``[FEAT=…]`` label),
with each rule's daughters and LFG equations. :func:`write_grammar_doc`
writes it to :data:`GRAMMAR_DOC_PATH`.

The ``tgllfg docs grammar`` CLI and the ``test_grammar_doc_sync`` gate
share this module, so the committed doc cannot drift from the rule
corpus (the "generate + check-in-sync" pattern, as for the audit
baseline and the planned ``openapi.json``).
"""

from pathlib import Path

from ..cfg.grammar import Grammar, Rule

# The generated reference lives at ``tlbe/docs/grammar.md``; from
# ``src/tgllfg/docs/grammar.py`` the tlbe root is ``parents[3]`` (the same
# anchor the audit package uses for ``data/tgl/``).
GRAMMAR_DOC_PATH = Path(__file__).resolve().parents[3] / "docs" / "grammar.md"


def _base(lhs: str) -> str:
    """Base non-terminal — the category before any ``[FEAT=…]`` label."""
    return lhs.split("[", 1)[0]


def render_grammar_doc(grammar: Grammar | None = None) -> str:
    """Render the grammar reference markdown for ``grammar`` (defaults to
    the composed default grammar)."""
    g = grammar if grammar is not None else Grammar.load_default()

    # Bucket by base category, preserving registration order within each.
    buckets: dict[str, list[Rule]] = {}
    for r in g.rules:
        buckets.setdefault(_base(r.lhs), []).append(r)
    cats = sorted(buckets)
    total = len(g.rules)
    n_lhs = len({r.lhs for r in g.rules})

    out: list[str] = []
    ap = out.append

    ap("<!-- Copyright (c) 2025-2026 G & R Associates LLC -->")
    ap("<!-- SPDX-License-Identifier: MIT OR Apache-2.0 -->")
    ap("<!-- markdownlint-disable-file MD013 -->")
    ap("<!-- Generated by `tgllfg docs grammar` — do not edit by hand. -->")
    ap("")
    ap("# tgllfg c-structure grammar")
    ap("")
    ap("Auto-generated reference for the Tagalog chart grammar in")
    ap("`src/tgllfg/cfg/` — every `Rule` composed by `Grammar.load_default()`,")
    ap("grouped by base non-terminal. The grammar is V-initial; see")
    ap("[`analysis-choices.md`](analysis-choices.md) for the linguistic")
    ap("rationale and [`architecture.md`](architecture.md) for where")
    ap("c-structure sits in the pipeline.")
    ap("")
    ap(
        f"**{total} rules across {n_lhs} labelled non-terminals "
        f"({len(cats)} base categories).** Equations use `↑` (the mother"
    )
    ap("f-structure) and `↓i` (the *i*-th daughter, 1-based); `=c` is a")
    ap("constraining equation, `¬` negation / absence, `∈` set membership.")
    ap("A trailing `[budget=N]` is a Phase 10.I per-span CNode-emission cap.")
    ap("")
    ap("Regenerate with `uv run tgllfg docs grammar` (`--check` verifies sync);")
    ap("the `test_grammar_doc_sync` test also fails if this file drifts.")
    ap("")
    ap("## Summary")
    ap("")
    ap("| Base non-terminal | Rules |")
    ap("| --- | --- |")
    for cat in cats:
        ap(f"| `{cat}` | {len(buckets[cat])} |")
    ap(f"| **Total** | **{total}** |")
    ap("")

    for cat in cats:
        ap(f"## {cat}")
        ap("")
        ap("```text")
        for i, r in enumerate(buckets[cat]):
            if i:
                ap("")
            rhs = " ".join(r.rhs) if r.rhs else "ε"
            ap(f"{r.lhs} → {rhs}")
            for eq in r.equations:
                ap(f"    {eq}")
            if r.budget is not None:
                ap(f"    [budget={r.budget}]")
        ap("```")
        ap("")

    return "\n".join(out).rstrip("\n") + "\n"


def write_grammar_doc(grammar: Grammar | None = None) -> Path:
    """Render and write ``docs/grammar.md``; return the path written."""
    GRAMMAR_DOC_PATH.write_text(render_grammar_doc(grammar), encoding="utf-8")
    return GRAMMAR_DOC_PATH
