// Copyright (c) 2025-2026 G & R Associates LLC
// SPDX-License-Identifier: MIT OR Apache-2.0

import { defineConfig } from "@hey-api/openapi-ts";

// Generates the typed axios SDK + TanStack Query artifacts from the
// committed root openapi.json (the Phase 13.D API contract). The output
// dir is regenerated by `npm run gen:api`; consumers import the SDK
// functions + the `*Options` / `*Mutation` query helpers from src/api/client.
export default defineConfig({
  input: "../openapi.json",
  output: "src/api/client",
  plugins: [
    "@hey-api/client-axios",
    {
      name: "@tanstack/react-query",
      queryOptions: true,
      queryKeys: true,
      infiniteQueryOptions: true,
      mutationOptions: true,
    },
  ],
});
