# Copyright (c) 2025-2026 G & R Associates LLC
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Phase 9.Z: naturalistic-tier audit regression test.

Loads ``tests/tgllfg/data/audit_regression_fixture.yaml`` (a
sampled subset of audit-corpus closures across Waves 1-4
generated by ``scripts/generate_audit_regression_fixture.py``)
and asserts that each fixture entry still parses with at least
the expected number of trees.

Serves as the canonical regression baseline that survives the
per-sub-PR test lifecycle: per-sub-PR test files
(``test_phase9*.py`` etc.) test the specific construction a
sub-PR added; this fixture tests that those closures *persist*
across all future churn — a single canonical baseline that
survives the inevitable refactor/delete cycle of per-sub-PR
tests.

Regenerate the fixture (``hatch run python
scripts/generate_audit_regression_fixture.py``) after Wave 4+
audits land or after major construction-class PRs change the
audit corpus shape. The fixture's checked-in YAML captures the
surface text directly, so this test runs cleanly on a fresh
clone even without the gitignored source corpora present.
"""

from pathlib import Path

import pytest
import yaml

from tgllfg.core.pipeline import parse_text


_FIXTURE_PATH = (
    Path(__file__).parent / "data" / "audit_regression_fixture.yaml"
)
_FIXTURE = yaml.safe_load(_FIXTURE_PATH.read_text(encoding="utf-8"))
_SAMPLES = _FIXTURE["samples"]


def _entry_id(entry: dict) -> str:
    """Test-id format: ``wave{N}/{source}/{locator}`` — readable
    in pytest's verbose output and grep-friendly."""
    return f"wave{entry['wave']}/{entry['source']}/{entry['locator']}"


@pytest.mark.parametrize(
    "entry", _SAMPLES, ids=[_entry_id(e) for e in _SAMPLES],
)
def test_audit_closure_persists(entry: dict) -> None:
    """Each fixture entry must still parse with ≥
    ``expected_parses_ge`` trees. Failure indicates a regression
    against the audit closure that was captured when the fixture
    was last regenerated."""
    parses = parse_text(entry["text"])
    expected = entry["expected_parses_ge"]
    assert len(parses) >= expected, (
        f"audit closure regression on {entry['source']}/"
        f"{entry['locator']}: expected ≥{expected} parses, "
        f"got {len(parses)} for: {entry['text']!r}"
    )


def test_fixture_metadata_present() -> None:
    """Fixture must carry the metadata block (phase /
    sampling_seed / target_sample_total / actual_sample_count /
    source) so re-generations are traceable to a known
    invocation."""
    meta = _FIXTURE["metadata"]
    assert meta["phase"] == "9.Z"
    assert meta["sampling_seed"] == 42
    assert meta["actual_sample_count"] == len(_SAMPLES)
    assert meta["source"].startswith(
        "audit parse-results from data/tgl/exemplars/"
    )


def test_fixture_covers_all_waves() -> None:
    """The fixture must include at least one sample from each
    of waves 1-4. If a wave drops out (e.g., because all of its
    parse-results.jsonl files are missing during regeneration),
    re-running the generator after a fresh audit should restore
    coverage."""
    waves_present = {s["wave"] for s in _SAMPLES}
    assert waves_present == {1, 2, 3, 4}, (
        f"fixture missing waves: {set(range(1, 5)) - waves_present}"
    )


def test_fixture_samples_are_deterministic_order() -> None:
    """Samples are sorted (wave, source, locator) so the YAML
    diff is review-friendly when the fixture regenerates."""
    keys = [(s["wave"], s["source"], s["locator"]) for s in _SAMPLES]
    assert keys == sorted(keys)
