"""Phase 5e Commit 14: AV mang- retain readings.

Schachter & Otanes 1972 §5.27 + Ramos 1971 paradigm tables note
that some bases admit a retain-pattern variant of the
``mang-`` distributive AV alongside the default drop pattern.
The retain pattern keeps the base's first consonant and adds a
homorganic nasal (the same ``nasal_assim_prefix`` op introduced
for Phase 5c §7.7's ``ipang-`` IV-INSTR / ``ika-`` IV-REASON):

* drop:   ``mang-`` + ``bili`` → mami → mamili / namili / namimili / mamimili
* retain: ``mang-`` + ``bili`` → namb → nambili / nambibili / mambibili

The two patterns can carry slightly different semantics
("habitual buyer" vs "engaging in buying activity") or be
dialectal variants. Per-base flagging via the new
``mang_retain`` affix class lets bases opt into the retain
pattern alongside the default drop pattern. The lex entries
(``BUY <SUBJ>`` etc.) are unchanged — both surface forms route
to the same PRED.

Currently only ``bili`` carries the ``mang_retain`` affix-class
flag; other roots can opt in by adding ``mang_retain`` to their
``affix_class`` list in ``data/tgl/roots.yaml``.
"""

from __future__ import annotations

from tgllfg.common import Token
from tgllfg.morph.analyzer import _get_default
from tgllfg.pipeline import parse_text


def _surface_to_features(surface: str) -> dict[str, object]:
    a = _get_default()
    t = Token(surface=surface, norm=surface.lower(), start=0, end=len(surface))
    analyses = a.analyze_one(t)
    assert analyses, f"no analysis for {surface!r}"
    assert analyses[0].pos == "VERB"
    return analyses[0].feats


# === Morph-level: retain pattern generates expected surfaces =============


class TestMorphLevel:
    """The new ``mang_retain`` cells generate the retain-pattern
    surfaces with the same VOICE/ASPECT features as the drop
    pattern."""

    def test_pfv_retain(self) -> None:
        """``nambili`` is generated by the new mang_retain PFV cell."""
        feats = _surface_to_features("nambili")
        assert feats.get("VOICE") == "AV"
        assert feats.get("ASPECT") == "PFV"

    def test_ipfv_retain(self) -> None:
        feats = _surface_to_features("nambibili")
        assert feats.get("ASPECT") == "IPFV"

    def test_ctpl_retain(self) -> None:
        feats = _surface_to_features("mambibili")
        assert feats.get("ASPECT") == "CTPL"

    def test_drop_pattern_unchanged(self) -> None:
        """The existing mang- drop forms still generate."""
        feats = _surface_to_features("namili")
        assert feats.get("ASPECT") == "PFV"

    def test_drop_ctpl_unchanged(self) -> None:
        feats = _surface_to_features("mamimili")
        assert feats.get("ASPECT") == "CTPL"


# === Parse level: both forms route to BUY <SUBJ> =========================


class TestParseLevel:
    """Both retain and drop surfaces parse with the same PRED
    via the existing bili AV-intr lex entry. The lex entry's
    ``transitive=False`` means it doesn't constrain TR, so it
    matches any AV form regardless of the surface pattern."""

    def test_retain_pfv_parses(self) -> None:
        rs = parse_text("Nambili ang nanay.", n_best=5)
        assert rs
        assert rs[0][1].feats.get("PRED") == "BUY <SUBJ>"
        assert rs[0][1].feats.get("ASPECT") == "PFV"

    def test_retain_ipfv_parses(self) -> None:
        rs = parse_text("Nambibili ang nanay.", n_best=5)
        assert rs
        assert rs[0][1].feats.get("PRED") == "BUY <SUBJ>"
        assert rs[0][1].feats.get("ASPECT") == "IPFV"

    def test_retain_ctpl_parses(self) -> None:
        rs = parse_text("Mambibili ang nanay.", n_best=5)
        assert rs
        assert rs[0][1].feats.get("PRED") == "BUY <SUBJ>"
        assert rs[0][1].feats.get("ASPECT") == "CTPL"

    def test_drop_form_still_parses(self) -> None:
        """Regression: drop-pattern ``namili`` still parses."""
        rs = parse_text("Namili ang nanay.", n_best=5)
        assert rs
        assert rs[0][1].feats.get("PRED") == "BUY <SUBJ>"
        assert rs[0][1].feats.get("ASPECT") == "PFV"

    def test_retain_with_negation(self) -> None:
        rs = parse_text("Hindi nambili ang nanay.", n_best=5)
        assert rs
        assert rs[0][1].feats.get("POLARITY") == "NEG"


# === Per-base flagging: kain doesn't admit retain pattern ===============


class TestPerBaseFlagging:
    """The ``mang_retain`` affix class is per-base. Only roots
    with ``mang_retain`` in their ``affix_class`` list generate
    the retain-pattern surfaces. ``kain`` is not flagged for
    retain (it has no ``mang_retain`` entry in its affix_class
    list); its mang- drop forms still generate, but no retain
    forms exist."""

    def test_kain_drop_pattern_works(self) -> None:
        """``kain`` is not in mang_retain's affix_class list; the
        drop pattern via the existing ``mang`` class still works
        (if applicable to kain). Actually kain doesn't have
        ``mang`` in its affix_class either — let's check
        instead that an unrelated retain-pattern surface doesn't
        spuriously generate."""
        # The retain-pattern surface for kain (if it existed)
        # would be `nankain` (PFV). kain isn't flagged for either
        # mang or mang_retain in the seed, so this should be _UNK.
        a = _get_default()
        t = Token(surface="nankain", norm="nankain", start=0, end=7)
        analyses = a.analyze_one(t)
        assert all(an.pos == "_UNK" for an in analyses)


# === LMT diagnostics ====================================================


class TestLmtDiagnostics:
    """Both drop and retain forms produce no blocking LMT
    diagnostics."""

    def test_no_blocking_retain(self) -> None:
        rs = parse_text("Nambili ang nanay.", n_best=5)
        for _, _f, _c, diags in rs:
            blocking = [d for d in diags if d.kind != "lmt-mismatch"]
            assert blocking == [], f"unexpected blocking diags: {blocking}"

    def test_no_blocking_drop(self) -> None:
        rs = parse_text("Namili ang nanay.", n_best=5)
        for _, _f, _c, diags in rs:
            blocking = [d for d in diags if d.kind != "lmt-mismatch"]
            assert blocking == [], f"unexpected blocking diags: {blocking}"
