"""Phase 4 §7.10: coverage benchmark harness.

Drives the corpus under
``tests/tgllfg/data/coverage_corpus.yaml`` (regenerated by
``scripts/generate_coverage_corpus.py``) through
:func:`parse_text_with_fragments` and asserts each sentence's
expected outcome:

* ``parse``    — at least one complete parse.
* ``fragment`` — no complete parse, but at least one fragment.
* ``fail``     — no parse and no fragment (intentionally
  out-of-scope construction or an unrecoverable failure mode).

The aggregate stats (per-construction full-parse rate) are
captured by :func:`test_coverage_summary` and rendered into
``docs/coverage.md`` by the user when re-running the benchmark.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

import pytest
import yaml

from tgllfg.pipeline import parse_text_with_fragments

_CORPUS_PATH = (
    Path(__file__).resolve().parent / "data" / "coverage_corpus.yaml"
)


def _load_corpus() -> list[dict]:
    with _CORPUS_PATH.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or []


_CORPUS = _load_corpus()


def _classify(text: str) -> str:
    """Run the pipeline and classify the outcome as
    ``parse`` / ``fragment`` / ``fail``."""
    result = parse_text_with_fragments(text)
    if result.parses:
        return "parse"
    if result.fragments:
        return "fragment"
    return "fail"


# === Per-sentence assertion ================================================
#
# Parametrize over the corpus. Each test asserts that the actual
# outcome matches the ``expected`` tag. Sentences tagged with
# ``parse`` must produce at least one complete parse; ``fragment``
# must produce at least one fragment with no complete parse;
# ``fail`` must produce neither (intentional out-of-scope).


@pytest.mark.parametrize(
    "entry",
    _CORPUS,
    ids=[f"{i}-{e['text'][:40]}" for i, e in enumerate(_CORPUS)],
)
def test_corpus_sentence(entry: dict) -> None:
    text = entry["text"]
    expected = entry["expected"]
    actual = _classify(text)
    if actual != expected:
        # Soft-fail: report mismatch but allow corpus to evolve.
        # Phase 4 §7.10 target is ~80% full-parse rate, not 100%
        # exact match. Use ``pytest --no-cov tests/tgllfg/test_coverage_phase4.py
        # -v`` to see all mismatches when iterating on the corpus.
        pytest.fail(
            f"{text!r}: expected={expected}, actual={actual} "
            f"(construction: {entry.get('construction', '?')})"
        )


# === Aggregate coverage report =============================================


def test_coverage_summary(tmp_path: Path) -> None:
    """Run the full corpus, collect per-construction stats, and
    write a summary JSON. The summary feeds the human-readable
    ``docs/coverage.md`` (regenerated by the user, not by tests)."""
    by_construction: dict[str, Counter[str]] = defaultdict(Counter)
    total = Counter[str]()
    for entry in _CORPUS:
        actual = _classify(entry["text"])
        construction = entry.get("construction", "?")
        # Strip the prefix-before-colon to get the §7.x section.
        section = construction.split(":", 1)[0]
        by_construction[section][actual] += 1
        total[actual] += 1

    summary = {
        "total_sentences": len(_CORPUS),
        "outcomes": dict(total),
        "by_section": {
            section: dict(counter)
            for section, counter in sorted(by_construction.items())
        },
    }
    out = tmp_path / "coverage_summary.json"
    out.write_text(json.dumps(summary, indent=2, sort_keys=True))

    # Phase 4 §7.10 deliverable: ~80% full-parse rate.
    parse_count = total.get("parse", 0)
    parse_rate = parse_count / len(_CORPUS) if _CORPUS else 0.0
    assert parse_rate >= 0.7, (
        f"Coverage parse-rate {parse_rate:.1%} below 70% floor; "
        f"summary={summary}"
    )


# === Smoke check the corpus loads ==========================================


def test_corpus_nonempty() -> None:
    assert len(_CORPUS) >= 500, f"corpus has {len(_CORPUS)} sentences (< 500)"


def test_corpus_entries_well_formed() -> None:
    """Every entry has ``text``, ``construction``, ``expected``."""
    for i, entry in enumerate(_CORPUS):
        assert "text" in entry, f"entry {i} missing text"
        assert "construction" in entry, f"entry {i} missing construction"
        assert "expected" in entry, f"entry {i} missing expected"
        assert entry["expected"] in ("parse", "fragment", "fail"), (
            f"entry {i} bad expected={entry['expected']!r}"
        )
