"""Phase 5n.A Commit 3 — SAY_CLASS / ASK_CLASS paradigm-engine propagation (§18 L91).

The §18.1 L91 entry described an "inconsistency in how the paradigm
engine projects ``feats:`` blocks", citing ``sabi`` (root) /
``sabihin`` as cells where SAY_CLASS=YES "fails to land", in contrast
to ``sinabi`` / ``sasabihin`` where it does. Audit (Phase 5n.A
Commit 3) showed the original characterisation was a misdiagnosis: the
projection IS uniform — every generated VERB cell of ``sabi`` carries
SAY_CLASS=YES; every generated cell of ``tanong`` carries
ASK_CLASS=YES. The cells the §18 entry called "missing" (``sabi`` bare
citation, ``sabihin`` OV-imperative, ``sabihan`` DV-imperative,
``tanong`` bare, ``tanungin`` OV-imperative) are not generated by the
paradigm engine at all — they're imperative-like surfaces that lack a
paradigm cell, not regular cells where the feat was being filtered out.

The "missing imperative cells" issue is a separate paradigm-engine gap
(potentially addressed by Phase 5n.A Commit 14's ``kainin`` paradigm
extension for L72), not a feat-projection bug.

These tests provide a comprehensive regression net: every surface the
analyzer indexes for ``sabi`` / ``tanong`` / ``payag`` / ``pilit`` /
``utos`` carries the lemma's root-level ``feats:`` block. The
projection mechanism is in
``src/tgllfg/morph/analyzer.py:_index_verb_paradigms`` (the
``for k, v in root.feats.items(): feats.setdefault(k, v)`` loop —
applied uniformly across every paradigm cell that fires for the root's
``affix_class``).
"""

from __future__ import annotations

import pytest

from tgllfg.morph import Analyzer


# === Universal SAY_CLASS / ASK_CLASS coverage =============================


class TestSayClassUniformProjection:
    """Every generated VERB surface for the ``sabi`` root carries
    SAY_CLASS=YES, regardless of voice / aspect / mood / affix-class."""

    def test_every_sabi_surface_carries_say_class(self) -> None:
        analyzer = Analyzer.from_default()
        surfaces_with_lemma_sabi: list[tuple[str, dict]] = []
        for surface, analyses in analyzer._index.verb_forms.items():
            for a in analyses:
                if a.lemma == "sabi":
                    surfaces_with_lemma_sabi.append((surface, dict(a.feats)))

        # Sanity: there should be many cells (mag-PFV/IPFV/CTPL/SOC,
        # in_oblig PFV/IPFV/CTPL, an_oblig PFV/IPFV/CTPL, maka
        # PFV/IPFV/CTPL/RECPFV).  The exact count varies with the
        # paradigm inventory; require at least 10.
        assert len(surfaces_with_lemma_sabi) >= 10, (
            f"unexpected sabi-cell coverage; got "
            f"{len(surfaces_with_lemma_sabi)} surfaces"
        )

        missing = [
            (surface, feats)
            for surface, feats in surfaces_with_lemma_sabi
            if feats.get("SAY_CLASS") != "YES"
        ]
        assert missing == [], (
            f"sabi cells missing SAY_CLASS=YES: "
            f"{[s for s, _ in missing]}"
        )


class TestAskClassUniformProjection:
    """Every generated VERB surface for the ``tanong`` root carries
    ASK_CLASS=YES, regardless of voice / aspect / mood / affix-class."""

    def test_every_tanong_surface_carries_ask_class(self) -> None:
        analyzer = Analyzer.from_default()
        surfaces_with_lemma_tanong: list[tuple[str, dict]] = []
        for surface, analyses in analyzer._index.verb_forms.items():
            for a in analyses:
                if a.lemma == "tanong":
                    surfaces_with_lemma_tanong.append((surface, dict(a.feats)))

        assert len(surfaces_with_lemma_tanong) >= 10, (
            f"unexpected tanong-cell coverage; got "
            f"{len(surfaces_with_lemma_tanong)} surfaces"
        )

        missing = [
            (surface, feats)
            for surface, feats in surfaces_with_lemma_tanong
            if feats.get("ASK_CLASS") != "YES"
        ]
        assert missing == [], (
            f"tanong cells missing ASK_CLASS=YES: "
            f"{[s for s, _ in missing]}"
        )


# === CTRL_CLASS propagation regression ====================================


CTRL_CLASS_ROOTS = [
    # (root, expected CTRL_CLASS)
    ("payag", "INTRANS"),
    ("pilit", "TRANS"),
    ("utos", "TRANS"),
]


@pytest.mark.parametrize("root,expected_ctrl", CTRL_CLASS_ROOTS)
def test_ctrl_class_uniform_projection(
    root: str, expected_ctrl: str
) -> None:
    """The control-class lex feat (Phase 4 §7.6) propagates uniformly
    across the root's generated cells. Pinned alongside SAY_CLASS /
    ASK_CLASS to confirm the propagation mechanism is consistent
    across all root-level feat keys."""
    analyzer = Analyzer.from_default()
    surfaces_with_lemma: list[tuple[str, dict]] = []
    for surface, analyses in analyzer._index.verb_forms.items():
        for a in analyses:
            if a.lemma == root:
                surfaces_with_lemma.append((surface, dict(a.feats)))

    assert len(surfaces_with_lemma) >= 6, (
        f"unexpected {root}-cell coverage; got "
        f"{len(surfaces_with_lemma)} surfaces"
    )

    mismatches = [
        (surface, feats.get("CTRL_CLASS"))
        for surface, feats in surfaces_with_lemma
        if feats.get("CTRL_CLASS") != expected_ctrl
    ]
    assert mismatches == [], (
        f"{root} cells mismatched CTRL_CLASS (expected "
        f"{expected_ctrl!r}): {mismatches}"
    )


# === Negative: roots without root-level feats stay clean ==================


class TestNoLeakageToOtherVerbs:
    """SAY_CLASS / ASK_CLASS / CTRL_CLASS!=NONE must not appear on
    verbs that don't declare the corresponding root-level feat. Plain
    verbs (``kain``, ``bili``, ``punta``, ``takbo``) carry the
    sentinel ``CTRL_CLASS=NONE`` (set by the indexer's defaults loop)
    but no SAY_CLASS / ASK_CLASS at all."""

    def _surfaces_for_lemma(self, analyzer: Analyzer, lemma: str):
        return [
            (s, dict(a.feats))
            for s, analyses in analyzer._index.verb_forms.items()
            for a in analyses
            if a.lemma == lemma
        ]

    @pytest.mark.parametrize("plain_root", ["kain", "bili", "punta", "takbo"])
    def test_no_say_class_on_plain_root(self, plain_root: str) -> None:
        analyzer = Analyzer.from_default()
        for surface, feats in self._surfaces_for_lemma(analyzer, plain_root):
            assert feats.get("SAY_CLASS") is None, (
                f"unexpected SAY_CLASS on {surface!r} "
                f"(lemma={plain_root!r})"
            )

    @pytest.mark.parametrize("plain_root", ["kain", "bili", "punta", "takbo"])
    def test_no_ask_class_on_plain_root(self, plain_root: str) -> None:
        analyzer = Analyzer.from_default()
        for surface, feats in self._surfaces_for_lemma(analyzer, plain_root):
            assert feats.get("ASK_CLASS") is None, (
                f"unexpected ASK_CLASS on {surface!r} "
                f"(lemma={plain_root!r})"
            )

    @pytest.mark.parametrize("plain_root", ["kain", "bili", "punta", "takbo"])
    def test_plain_root_has_ctrl_class_set(self, plain_root: str) -> None:
        """Plain verbs (no root-level CTRL_CLASS) get either:

        * the ``CTRL_CLASS=NONE`` sentinel from the indexer's
          defaults loop (line ~418 in analyzer.py) on cells that
          don't set CTRL_CLASS, or
        * a cell-level CTRL_CLASS override (the ``magpa`` /
          ``pa_in`` / ``pa_an`` causative cells set
          ``CTRL_CLASS=INTRANS`` because the magpa-causative is
          intrinsically a control structure).

        Either way, CTRL_CLASS is always present (never missing) so
        the grammar's ``V[CTRL_CLASS=X]`` patterns can match without
        ambiguity. This test pins that invariant."""
        analyzer = Analyzer.from_default()
        surfaces = self._surfaces_for_lemma(analyzer, plain_root)
        assert surfaces, f"no surfaces found for {plain_root!r}"
        valid_values = {"NONE", "INTRANS", "TRANS", "PSYCH"}
        for surface, feats in surfaces:
            assert feats.get("CTRL_CLASS") in valid_values, (
                f"plain root {plain_root!r} surface {surface!r} has "
                f"unexpected CTRL_CLASS={feats.get('CTRL_CLASS')!r}; "
                f"expected one of {valid_values}"
            )
