// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { auditDiff, auditRun, auditRunStatus, health, lexSearch, type Options, parse, ready } from '../sdk.gen';
import type { AuditDiffData, AuditDiffError, AuditDiffResponse, AuditRunData, AuditRunError, AuditRunResponse, AuditRunStatusData, AuditRunStatusError, AuditRunStatusResponse, HealthData, HealthResponse, LexSearchData, LexSearchError, LexSearchResponse2, ParseData, ParseError, ParseResponse2, ReadyData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 *
 * Liveness: the process is up and serving. No external deps.
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse, AxiosError<DefaultError>, HealthResponse, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const readyQueryKey = (options?: Options<ReadyData>) => createQueryKey('ready', options);

/**
 * Ready
 *
 * Readiness: DB reachable **and** the compiled grammar warmed.
 * Returns ``503`` with a per-check breakdown until both hold.
 */
export const readyOptions = (options?: Options<ReadyData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof readyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ready({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readyQueryKey(options)
});

/**
 * Parse a Tagalog sentence
 */
export const parseMutation = (options?: Partial<Options<ParseData>>): UseMutationOptions<ParseResponse2, AxiosError<ParseError>, Options<ParseData>> => {
    const mutationOptions: UseMutationOptions<ParseResponse2, AxiosError<ParseError>, Options<ParseData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await parse({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lexSearchQueryKey = (options: Options<LexSearchData>) => createQueryKey('lexSearch', options);

/**
 * Fuzzy lemma search
 */
export const lexSearchOptions = (options: Options<LexSearchData>) => queryOptions<LexSearchResponse2, AxiosError<LexSearchError>, LexSearchResponse2, ReturnType<typeof lexSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lexSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lexSearchQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const lexSearchInfiniteQueryKey = (options: Options<LexSearchData>): QueryKey<Options<LexSearchData>> => createQueryKey('lexSearch', options, true);

/**
 * Fuzzy lemma search
 */
export const lexSearchInfiniteOptions = (options: Options<LexSearchData>) => infiniteQueryOptions<LexSearchResponse2, AxiosError<LexSearchError>, InfiniteData<LexSearchResponse2>, QueryKey<Options<LexSearchData>>, number | null | Pick<QueryKey<Options<LexSearchData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<LexSearchData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await lexSearch({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lexSearchInfiniteQueryKey(options)
});

/**
 * Start a corpus audit (background job)
 */
export const auditRunMutation = (options?: Partial<Options<AuditRunData>>): UseMutationOptions<AuditRunResponse, AxiosError<AuditRunError>, Options<AuditRunData>> => {
    const mutationOptions: UseMutationOptions<AuditRunResponse, AxiosError<AuditRunError>, Options<AuditRunData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await auditRun({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const auditRunStatusQueryKey = (options: Options<AuditRunStatusData>) => createQueryKey('auditRunStatus', options);

/**
 * Poll an audit run's status
 */
export const auditRunStatusOptions = (options: Options<AuditRunStatusData>) => queryOptions<AuditRunStatusResponse, AxiosError<AuditRunStatusError>, AuditRunStatusResponse, ReturnType<typeof auditRunStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await auditRunStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: auditRunStatusQueryKey(options)
});

/**
 * Diff the latest results against the baseline
 */
export const auditDiffMutation = (options?: Partial<Options<AuditDiffData>>): UseMutationOptions<AuditDiffResponse, AxiosError<AuditDiffError>, Options<AuditDiffData>> => {
    const mutationOptions: UseMutationOptions<AuditDiffResponse, AxiosError<AuditDiffError>, Options<AuditDiffData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await auditDiff({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
