// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { auditDiffApiV1AuditDiffPost, auditRunApiV1AuditRunPost, auditRunStatusApiV1AuditRunsRunIdGet, healthHealthGet, lexSearchApiV1LexSearchGet, type Options, parseEndpointApiV1ParsePost, readyReadyGet } from '../sdk.gen';
import type { AuditDiffApiV1AuditDiffPostData, AuditDiffApiV1AuditDiffPostError, AuditDiffApiV1AuditDiffPostResponse, AuditRunApiV1AuditRunPostData, AuditRunApiV1AuditRunPostError, AuditRunApiV1AuditRunPostResponse, AuditRunStatusApiV1AuditRunsRunIdGetData, AuditRunStatusApiV1AuditRunsRunIdGetError, AuditRunStatusApiV1AuditRunsRunIdGetResponse, HealthHealthGetData, HealthHealthGetResponse, LexSearchApiV1LexSearchGetData, LexSearchApiV1LexSearchGetError, LexSearchApiV1LexSearchGetResponse, ParseEndpointApiV1ParsePostData, ParseEndpointApiV1ParsePostError, ParseEndpointApiV1ParsePostResponse, ReadyReadyGetData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthHealthGetQueryKey = (options?: Options<HealthHealthGetData>) => createQueryKey('healthHealthGet', options);

/**
 * Health
 *
 * Liveness: the process is up and serving. No external deps.
 */
export const healthHealthGetOptions = (options?: Options<HealthHealthGetData>) => queryOptions<HealthHealthGetResponse, AxiosError<DefaultError>, HealthHealthGetResponse, ReturnType<typeof healthHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthHealthGetQueryKey(options)
});

export const readyReadyGetQueryKey = (options?: Options<ReadyReadyGetData>) => createQueryKey('readyReadyGet', options);

/**
 * Ready
 *
 * Readiness: DB reachable **and** the compiled grammar warmed.
 * Returns ``503`` with a per-check breakdown until both hold.
 */
export const readyReadyGetOptions = (options?: Options<ReadyReadyGetData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof readyReadyGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readyReadyGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readyReadyGetQueryKey(options)
});

/**
 * Parse a Tagalog sentence
 */
export const parseEndpointApiV1ParsePostMutation = (options?: Partial<Options<ParseEndpointApiV1ParsePostData>>): UseMutationOptions<ParseEndpointApiV1ParsePostResponse, AxiosError<ParseEndpointApiV1ParsePostError>, Options<ParseEndpointApiV1ParsePostData>> => {
    const mutationOptions: UseMutationOptions<ParseEndpointApiV1ParsePostResponse, AxiosError<ParseEndpointApiV1ParsePostError>, Options<ParseEndpointApiV1ParsePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await parseEndpointApiV1ParsePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lexSearchApiV1LexSearchGetQueryKey = (options: Options<LexSearchApiV1LexSearchGetData>) => createQueryKey('lexSearchApiV1LexSearchGet', options);

/**
 * Fuzzy lemma search
 */
export const lexSearchApiV1LexSearchGetOptions = (options: Options<LexSearchApiV1LexSearchGetData>) => queryOptions<LexSearchApiV1LexSearchGetResponse, AxiosError<LexSearchApiV1LexSearchGetError>, LexSearchApiV1LexSearchGetResponse, ReturnType<typeof lexSearchApiV1LexSearchGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lexSearchApiV1LexSearchGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lexSearchApiV1LexSearchGetQueryKey(options)
});

/**
 * Start a corpus audit (background job)
 */
export const auditRunApiV1AuditRunPostMutation = (options?: Partial<Options<AuditRunApiV1AuditRunPostData>>): UseMutationOptions<AuditRunApiV1AuditRunPostResponse, AxiosError<AuditRunApiV1AuditRunPostError>, Options<AuditRunApiV1AuditRunPostData>> => {
    const mutationOptions: UseMutationOptions<AuditRunApiV1AuditRunPostResponse, AxiosError<AuditRunApiV1AuditRunPostError>, Options<AuditRunApiV1AuditRunPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await auditRunApiV1AuditRunPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const auditRunStatusApiV1AuditRunsRunIdGetQueryKey = (options: Options<AuditRunStatusApiV1AuditRunsRunIdGetData>) => createQueryKey('auditRunStatusApiV1AuditRunsRunIdGet', options);

/**
 * Poll an audit run's status
 */
export const auditRunStatusApiV1AuditRunsRunIdGetOptions = (options: Options<AuditRunStatusApiV1AuditRunsRunIdGetData>) => queryOptions<AuditRunStatusApiV1AuditRunsRunIdGetResponse, AxiosError<AuditRunStatusApiV1AuditRunsRunIdGetError>, AuditRunStatusApiV1AuditRunsRunIdGetResponse, ReturnType<typeof auditRunStatusApiV1AuditRunsRunIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await auditRunStatusApiV1AuditRunsRunIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: auditRunStatusApiV1AuditRunsRunIdGetQueryKey(options)
});

/**
 * Diff the latest results against the baseline
 */
export const auditDiffApiV1AuditDiffPostMutation = (options?: Partial<Options<AuditDiffApiV1AuditDiffPostData>>): UseMutationOptions<AuditDiffApiV1AuditDiffPostResponse, AxiosError<AuditDiffApiV1AuditDiffPostError>, Options<AuditDiffApiV1AuditDiffPostData>> => {
    const mutationOptions: UseMutationOptions<AuditDiffApiV1AuditDiffPostResponse, AxiosError<AuditDiffApiV1AuditDiffPostError>, Options<AuditDiffApiV1AuditDiffPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await auditDiffApiV1AuditDiffPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
